# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence',
            field=models.CharField(blank=True, max_length=100, verbose_name='Residence'),
        ),
    ]
