BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBB

BBBBB BBBBB gettext('Create Lecture') BBBBBBBB BBBBB
BBBBB BBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBB BBBBBB
BBBBB BBBBB gettext('Create Lecture') BBBBBBBB BBBBB
