BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBB

BBBBB BBBBBBB
  XX XXXXXXXXXXXXXXXXXXX
    XX XXXXXBBB BBBBBBBBBBBBBBBB XXXXXXXXXX XXXXXXXXXXXXX gettext('Add Mooc ') XXXX
  XXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
          XXXX
              XXXX gettext('Lecture') XXXXX
          XXXXX
      XXXXXXXX
      XXXXXXX
        BBB B BB BBBBB
				XXX XXXXXXXXXX XXXXXXXX
				  XXXXXXXXX
          XXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBX  XXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX
          XXX XXXXXXXXXXXXXXX
            XX XXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBB XXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXX
				XXXXX
        BBBBB
			XXXX
				XXXXXXXX XXXXXX XXX XX XXXXXXXX XXXXXXXXX
			XXXXX
        BBBBBB
    	
      XXXXXXXX
  XXXXXXXX


	XXX  XXXX
XXXXXX
BBBBBBBB BBBBBBB