BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBB

BBBBBBBB
BBBBB BBBBBBB
	XXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXX
		XXX XXXXXXXXXXXXX
			BBB B BB BBBBBBBBBBBBBBBBBBBBBBB
				XXX XXXXXXXXXX BB B BB BBBBBB XXXXXXXXXXXXXXXXBBBBBX
					XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBXX
					XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXFFFFFXXXXXXXXXXX
						
					XXXX
				XXXXX
			BBBBB
				XXXXXX XXXXXXX XXXXXXXXX
			BBBBBB
		XXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXX
		BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBB
			BBBB BBBBBBBBBBBBBBBBB
				XXXXXXXXX
				
			BBBBBBB
		BBBBBB
	XXXXXX
BBBBBBBB BBBBBBB