BBBBBBB BBBBBBBBBBBBBBBBBBBB	

BBBBB BBBBBBB
	BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXXXXX
		XXXX XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX
		XXX
			XX XXXXXXXXXXXXX
			 XXXXXXXX
			XXXXXXXXXXX 
		XXXX
		BBBBBBBBBB BBB
			FFFFFFFFFF
		BBBBBBBBBBBBB
		BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
			XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
			
			BBBBBBBBBB
			XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX
			XXXXXXX
			BBBB
			XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
			XXXXXXXX XX XXXXXX
		XXXX
		BBBBB
		XXXXXX
	BBBBBBB
BBBBBBBB