XXXXXXXXX XXXXX
XXXXXX
XXXXXX
XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
 XXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
XXXXXXXX
XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXX XXX X XXXXXXXXXXXXXXXXXXXX

XXXXXXXX XXXXXX XX X
    XXXXXXXXXXXXXXXXXX
    XXX XXXX X XXXXX XXXXXXXXXXX X XXX X XXXXX
    XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XX
X

XXX XXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXX XX X XXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXX
    XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
X XXXX X
    XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX X XXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXX
    XXX
X
XXXXXXXXX
XXXXXXX
XXXXXXX