XXXXXXXXX XXXXX
XXXXXX
XXXXXX
XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXX XXXXXXXXXXXX X XXXX XXX XXX XXX XXX XXX XXX XXX XXX XXX XXXXX XXX XXXXX XXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXXXXX XXX
XXXXX X XXXXXXXXX XXX X XXXXX XXXXXXXXXXXX XXXXXX XXX X XXXX XXXX XXXXX XXXXXX XXX X XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX X XXXXXX XXXXXXX XXXXXX X XXXXXX XXXXXXXX
XXXXXXX XXXX XXXX XX XXXXX XX XXXXXX XXX XXXX XXXXXX XX XXXXXXX XXXX
XXX XXXXXXXXXXXXXXXXXX X XXXXXX XXX XXXXXX XXXXX XXXXXXXXXXXXXX XXX 
XXX XXX X XX

XXXXXXXX XXXXXXXXXXXXX X
    XXXXXX XXXXXXXX XXXX X
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXX
            XXXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXX

        XXX XX X XXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXX XXXXX XXXX X X XXXXXXXX
        XX XXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXXXX X
            XXX XXXXX X XXXXXXXXXXXXXXXX
            XXX XXXX X XXXXXXXXXXXXXXXXXX XXX
            XX XXXXXXXX XXX XXXXXXXX X
                XXXXXXXXXXXXXXXXX
            X XXXX XX XXXXXXXX XXX XXXXXX X
                XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
                XXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXXX XXXXXXX X X X X XXXX
            X
        XXX
    XX
X

XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
    XXXXXX XXXXXXXXXXXXXX
XXX

XXXXXXXXXXXXXX X XXXXXXXXX XXXXX XX X XXXXXXXXX
XXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXX X XXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXX
    XXX
XX XXXXXX
XXXXXXXXX
XXXXXXX
XXXXXXX