# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('category', models.CharField(choices=[('', 'Select a category'), ('news', 'News'), ('event', 'Event')], max_length=5)),
                ('category_fr', models.CharField(choices=[('', 'Select a category'), ('news', 'News'), ('event', 'Event')], max_length=5, null=True)),
                ('category_en', models.CharField(choices=[('', 'Select a category'), ('news', 'News'), ('event', 'Event')], max_length=5, null=True)),
                ('title', models.CharField(max_length=150)),
                ('title_fr', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('content', models.TextField()),
                ('content_fr', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('picture', models.ImageField(upload_to='image/')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
