# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_fr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
