# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 10:06
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20160921_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content_en',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content_fr',
            field=djrichtextfield.models.RichTextField(null=True),
        ),
    ]
