# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_auto_20161010_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content_fr',
            field=models.TextField(null=True),
        ),
    ]
