# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasine',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sommary',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
