# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-15 19:29
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160918_1700'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianzaAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Allianza Admins',
                'verbose_name': 'Allianza Admin',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
