# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.Option')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('name', models.CharField(max_length=100, verbose_name='Name(s)')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('birth_venue', models.CharField(max_length=200, verbose_name="Birth Venue (for example 'Surulere, Lagos')")),
                ('number', models.IntegerField(unique=True)),
                ('matricule_number', models.CharField(max_length=10, verbose_name='Matricule Number')),
                ('defense_score', models.FloatField(blank=True, null=True, verbose_name='Defense Score')),
                ('mention', models.CharField(blank=True, max_length=50)),
                ('class_of_degree', models.CharField(blank=True, max_length=100, verbose_name='Class of Degree')),
                ('is_print', models.BooleanField(default=False, verbose_name='Is Print')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Bachelor',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduation.Student')),
                ('option', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='graduation.Option', verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Bachelor',
                'verbose_name_plural': 'Bachelors',
            },
            bases=('graduation.student',),
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduation.Student')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.Speciality')),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
            },
            bases=('graduation.student',),
        ),
    ]
