BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB

BBBBB BBBBBBBBBBB

  XXXX gettext('Confirm E-mail Address') XXXXX

BBBBBBBB BBBBBBBBBBB


BBBBB BBBBBBBBBB

        BB BBBBBBBBBBBB

        BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB

        XXX gettext('Please confirm that <a href="mailto:%(email)s">%(email)s</a> is an e-mail address for user %(user_display)s.') SSSSSS SSSSSSS SSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS SS SSSSSS SSSSSSS SSS SSSS SSSSSSSSSSSSSSSSSXXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBXX
        BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext('Confirm') XXXXXXXXX
        XXXXXXX

        BBBB

        BBB BBBBBBBBBBBBBBB BB BBBBBBBBB

        XXX gettext('This e-mail confirmation link expired or is invalid. Please <a href="%(email_url)s">issue a new e-mail confirmation request</a>.') SSSS SSSSSS SSSSSSSSSSSS SSSS SSSSSSS SS SS SSSSSSSS SSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSS S SSS SSSSSS SSSSSSSSSSSS SSSSSSSSSSSSXXXX

        BBBBB

BBBBBBBB BBBBBBBBBB
