BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext('Account') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX gettext('E-mail Addresses') XXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBB
      XXX gettext('The following e-mail addresses are associated with your account:') XXXX

      XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXXXXXXX XXXXXXXXXXXXXXXXXXXX

        BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBBXX

            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXX

      
          BB BBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXXXXXXX gettext('Verified') XXXXXXX
          BBBB
          XXXXX XXXXXXXXXXXXXXXXXXX gettext('Unverified') XXXXXXX
          BBBBB
            BB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX gettext('Primary') XXXXXXXBBBBB
      XXXXXXXX
      XXXXXX
        BBBBBB

      XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X gettext('Make Primary') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X gettext('Re-send Verification') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X gettext('Remove') XXXXXXXXX
      XXXXXX

      XXXXXXXXXXX
      XXXXXXX

      BBBB
      XXXXXXXXXXX gettext('Warning:') XXXXXXXXX  gettext('You currently do not have any e-mail address set up. You should really add an e-mail address so you can receive notifications, reset your password, etc.') XXXX

      BBBBB


          XXXX gettext('Add E-mail Address') XXXXX

          XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
              BBBBBBBBBB
              FFFFFF
              XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext('Add E-mail') XXXXXXXXX
          XXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB


BBBBB BBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXX X
  XXX XXXXXXX X X gettext('Do you really want to remove the selected e-mail address?') XX
  XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
      XX XX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX
      X
    XXX
  X
XXXXX
XXXXXXXXX
BBBBBBBB
