BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB

BBBBB BBBBBBBBBBB

  XXXX gettext('Confirm E-mail Address') XXXXX

BBBBBBBB BBBBBBBBBBB


BBBBB BBBBBBBBBB

  BBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB

  XXX gettext('You have confirmed that <a href="mailto:%(email)s">%(email)s</a> is an e-mail address for user %(user_display)s.') SSS SSSS SSSSSSSSS SSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS SS SSSSSS SSSSSSS SSS SSSS SSSSSSSSSSSSSSSSSXXXX

BBBBBBBB BBBBBBBBBB
