BBBBBBB BBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXBBBBBBBB BBBBB
BBBBB BBBBBBBBB gettext(' Please Sign In') BBBBBBBB BBBBBBBBB

BBBBB BBBB

  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX

          XXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext('Please Sign In') 
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBXX
              BBBBBBBBBB
              FFFFFF
              BB BBBBBBBBBBBBBBBBBBBB
              XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
              BBBBB
              XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX gettext('Sign In') XXXXXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
        XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX gettext('Have you forgotten your Password? Click here to reset it !') XXXX
      XXXXXX
    XXXXXX
  XXXXXX

BBBBBBBB BBBB
