BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBBB

  XXXX gettext('Sign Out') XXXXX

BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB

  XXX gettext('Are you sure you want to sign out?') XXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
    BBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
    BBBBB
    XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext('Sign Out') XXXXXXXXX
  XXXXXXX

BBBBBBBB BBBBBBBBBB
