BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB

BBBBB BBBBBBBBBBB

  XXXX gettext('Password Reset') XXXXX

BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB

  BB BBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB

  XXX gettext('We have sent you an e-mail. Please contact us if you do not receive it within a few minutes.') SS SSSS SSSS SSS SS SSSSSSS SSSSSS SSSSSSS SS SS SSS SS SSS SSSSSSS SS SSSSSS S SSS SSSSSSSSXXXX

BBBBBBBB BBBBBBBBBB
