BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB

  XXXXBB BBBBBBBBBB gettext('Bad Token') BBBB gettext('Change Password') BBBBBXXXXX

BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB

  BB BBBBBBBBBB
      BBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
      XXX gettext('The password reset link was invalid, possibly because it has already been used.  Please request a <a href="%(passwd_reset_url)s">new password reset</a>.') SSS SSSSSSSS SSSSS SSSS SSS SSSSSSSS SSSSSSSS SSSSSSS SS SSS SSSSSSS SSSS SSSSS  SSSSSS SSSSSSS S SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSS SSSSSSSSSSXXXX
  BBBB
      BB BBBB
          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
              BBBBBBBBBB
              FFFFFF
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX gettext('change password') XXXXXXXXX
          XXXXXXX
      BBBB
          XXX gettext('Your password is now changed.') XXXX
      BBBBB
  BBBBB
  
BBBBBBBB BBBBBBBBBB
