BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBBB BBBBBBBBBBB

  XXXX gettext('Change Password') XXXXX

BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB

  XXX gettext('Your password is now changed.') XXXX

BBBBBBBB BBBBBBBBBB
