BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB

  XXXX gettext('Password Reset') XXXXX

BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB

  BB BBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB

  XX XXXXXXXXXXXXXXXXXX gettext("Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it.") XXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      FFFFFF
      XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXX gettext('Reset My Password') XXXXXXXXX
  XXXXXXX

BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBBB
    
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
BBBBBBBB BBBBBBBBBB
