
BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB

  XXXX gettext('Set Password') XXXXX

BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      FFFFFF
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext('Set Password') XXX
  XXXXXXX

BBBBBBBB BBBBBBBBBB
