BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBB gettext('Change Password') BBBBBBBB

BBBBB BBBBB gettext('Password Update') BBBBBBBB BBBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext('Change Password') 
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              BBBBBBBBBB
              FFFFFF
              XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX gettext('Change Password') XXXXXXXXX
          XXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB
