BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB gettext('Signup') BBBBBBBB BBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX gettext('Sign Up') XXXXX

      XXX gettext('Already have an account? Then please <a href="%(login_url)s">sign in</a>.') SSSSSSS SSSS SS SSSSSSSS SSSS SSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSXXXX

      XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
        BBBBBBBBBB
        FFFFFF
        BB BBBBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
        BBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext('Sign Up')  XXXXXXXXXXXXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX
XXXXXX


BBBBBBBB BBBBBBB



