BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBBB

  XXXX gettext('Verify Your E-mail Address') XXXXX

BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB

  XX XXXXXXXXXXXXXXXXXX gettext('We have sent an e-mail to <a href="mailto:%(email)s">%(email)s</a> for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes.') SS SSSS SSSS SS SSSSSS SS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSS SSSSSSSSSSSSS SSSSSS SSS SSSS SSSSSSSS SS SSSSSSSS SSS SSSSSS SSSSSSSS SSSSSS SSSSSSS SS SS SSS SS SSS SSSSSSS SS SSSSSS S SSS SSSSSSSSXXXX

BBBBBBBB BBBBBBBBBB
