BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB
	XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XBBBBBBBBBB
	    
	  	XXX gettext('by clicking the button below, you confirm that you accept the ')  XX XXXXXXXX gettext('rules and conditions of ...') XXXXXXXXXXXXXXXX
	    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext('validate') X XX
	XXXXXXX
BBBBBBBB BBBBBBBBBBBB