BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB
	XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XBBBBBBBBBB
	    
	    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext('validate') X XX
	XXXXXXX
BBBBBBBB BBBBBBBBBBBB