# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-01 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import foton.courses.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElearningProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('pdf', models.FileField(blank=True, upload_to='pdf/')),
            ],
            options={
                'verbose_name': 'E-Program',
                'verbose_name_plural': 'E-Programs',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Course')),
                ('credits', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
            },
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='LectureModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Module')),
                ('order', foton.courses.forms.OrderField(blank=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='elearning.Lecture')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
            bases=('courses.module',),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='Semester', max_length=9)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='ElearningBachelor',
            fields=[
                ('elearningprogram_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elearning.ElearningProgram')),
            ],
            options={
                'verbose_name': 'E-Bachelor',
                'verbose_name_plural': 'E-Bachelors',
            },
            bases=('elearning.elearningprogram',),
        ),
        migrations.CreateModel(
            name='ElearningMaster',
            fields=[
                ('elearningprogram_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elearning.ElearningProgram')),
            ],
            options={
                'verbose_name': 'E-Master',
                'verbose_name_plural': 'E-Masters',
            },
            bases=('elearning.elearningprogram',),
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.ElearningProgram'),
        ),
    ]
