# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-01 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_lecturer', to='universities.Lecturer'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.Semester'),
        ),
        migrations.AddField(
            model_name='elearningprogram',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='program_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('name', 'order', 'program')]),
        ),
        migrations.AddField(
            model_name='elearningmaster',
            name='speciality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.Speciality'),
        ),
        migrations.AddField(
            model_name='elearningbachelor',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Option'),
        ),
    ]
