# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_allianzaregistred_allianzastudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianzastudent',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearning.ElearningProgram'),
            preserve_default=False,
        ),
    ]
