# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-16 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_allianzastudent_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearningprogram',
            name='description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elearningprogram',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Overview Image'),
            preserve_default=False,
        ),
    ]
