# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-20 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_auto_20170316_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_lecturer', to=settings.AUTH_USER_MODEL),
        ),
    ]
