BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBB
	XXXX XXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX
						BBB B BB BBBBBBB
							XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBXXXXXXXXXXX					
						BBBBBB				
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX
						XXX
							BBB BBBBBBBBBB BB BBBBBBBBBBB
								XX XXXXXXXXX  XXXX XXXXXXXX 
								XXXX
							BBBBBB
						XXXX
						BBB B BB BBBBBBBBBBB
						XXXXX
							XXX XXXXXX  XXXXX
							BBBB BBBBBBBBBBB   
								BBB B BB BBBBBBB
									BB BBBBBBBBBBBBBBBBB BB BBBB
										XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBXXXXXX
									BBBBB
								BBBBBB
							BBBBBBB

						XXXXXX
						BBBBBB
						
					XXXXXX
				XXXXXX

XXXX 				XXXX XXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXX
					
					XXXXXX
				XXXXXX XXX
			XXXXXX
		XXXXXX
	XXXXXX
BBBBBBBB BBBB