BBBBBBB BBBBBBBBBBBBBBBBBBBB

BBBBB BBBB
	XXXX XXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX
						BBB B BB BBBBBBB
							XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBXXXXXXXXXXX					
						BBBBBB				
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX
						
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXX
						BBBBB BBBBBBBBBBBBBBB

						BBBBBBBB BBBBBBBBBBBBBBB
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
BBBBBBBB BBBB