# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 16:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('staff', '0001_initial'),
        ('degrees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.IntegerField(choices=[('', 'Choose your gender'), (0, 'Female'), (1, 'Male')])),
                ('student_type', models.IntegerField(choices=[('', 'Choose your type'), (0, 'Regular Student'), (1, 'Allianza Student')])),
                ('origin', django_countries.fields.CountryField(max_length=2)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('birth_venue', models.CharField(max_length=100)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Year')),
            ],
            options={
                'verbose_name_plural': 'Students',
                'verbose_name': 'Student',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='registred',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='registred',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degrees.Program'),
        ),
    ]
