# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20160908_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.IntegerField(default=1),
        ),
    ]
