# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='matricule',
        ),
        migrations.AddField(
            model_name='registred',
            name='matricule',
            field=models.IntegerField(default=1),
        ),
    ]
