# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-10 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20160910_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='registred',
            name='matricule_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
