# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_registred_matricule_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name_fr',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registred',
            name='clazz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='registred',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
