# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20160913_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registred',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class', verbose_name='Class'),
        ),
    ]
