# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20160913_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
