# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20160913_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='full_name',
            field=models.CharField(blank=True, max_length=51, unique=True),
        ),
    ]
