# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_class_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.IntegerField(choices=[('', 'Choose your marital status'), (0, 'Single'), (1, 'Maried')], default=0, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='student',
            name='national_Id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_venue',
            field=models.CharField(max_length=100, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[('', 'Choose your gender'), (0, 'Female'), (1, 'Male')], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='origin',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.IntegerField(choices=[('', 'Choose your type'), (0, 'Regular Student')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Year', verbose_name='Academic Year'),
        ),
    ]
