# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20160915_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sponsor_address',
            field=models.CharField(help_text='Sponsor or Guardian Permanent Address', max_length=50, verbose_name='Sponsor or Guardian Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor_relationship',
            field=models.CharField(help_text='Relation to Applicant', max_length=50, verbose_name='Relationship with Sponsor or Guardian'),
        ),
    ]
