# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20160918_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.IntegerField(choices=[('', 'Choose your type'), (0, 'Regular Student')], default=0, verbose_name='Type'),
        ),
    ]
