# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-11 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20170311_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sponsor_full_name',
            field=models.CharField(max_length=100, verbose_name='Sponsor or guardian full name'),
        ),
    ]
