# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-11 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20170311_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth Date'),
        ),
    ]
