# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20170311_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.IntegerField(choices=[('', 'Choose your type'), (0, 'Regular Student'), (1, 'Allianza Student')], default=0, verbose_name='Type'),
        ),
    ]
