# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20170311_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registred',
            name='clazz',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.Class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor_address',
            field=models.CharField(blank=True, help_text='Sponsor or Guardian Permanent Address', max_length=50, verbose_name='Sponsor or Guardian Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Sponsor or Guardian Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor_full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sponsor or guardian full name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor_occupation',
            field=models.CharField(blank=True, max_length=150, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sponsor or Guardian Telphone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor_relationship',
            field=models.CharField(blank=True, help_text='Relation to Applicant', max_length=50, verbose_name='Relationship with Sponsor or Guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.IntegerField(choices=[('', 'Choose your type'), (0, 'Regular Student'), (1, 'Allianza Student')], default=1, verbose_name='Type'),
        ),
    ]
