# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20170315_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registred',
            name='clazz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Class', verbose_name='Class'),
        ),
    ]
