BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBB

BBBBB BBBBBBB

XX XXXXXXXXXXXXXXXXXX X
	XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX gettext('Add or Edit Modules') XXXX
	
XXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
          XXXX
              XXXX gettext('Modules') XXXXX
          XXXXX
      XXXXXXXX
      XXXXXXX
        BBB B BB BBBBBBB
			XXX XXXXXXXXXX XXXXXXXX
			  XXXXXXXXX
			  XXX XXXXXXXXXXXXXXX
			    XX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBB XXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
			  XXXXX
			XXXXX
        BBBBB
			XXXX
				XXXXXXXX XXXXXX XXX XX XXXXXXXX XXXXXXXXX
			XXXXX
        BBBBBB
    	
      XXXXXXXX
  XXXXXXXX
XXXXXX
BBBBBBBB BBBBBBB