# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('intro', models.TextField(verbose_name='Content')),
                ('intro_fr', models.TextField(null=True, verbose_name='Content')),
                ('intro_en', models.TextField(null=True, verbose_name='Content')),
                ('slug', models.SlugField(default='', verbose_name='slug')),
                ('slug_fr', models.SlugField(default='', null=True, verbose_name='slug')),
                ('slug_en', models.SlugField(default='', null=True, verbose_name='slug')),
                ('image', models.ImageField(upload_to='image/')),
            ],
            options={
                'verbose_name_plural': 'Abouts',
                'verbose_name': 'About',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('slug', models.SlugField(default='')),
                ('slug_fr', models.SlugField(default='', null=True)),
                ('slug_en', models.SlugField(default='', null=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='image/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='presentation.About')),
                ('about_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='presentation.About')),
                ('about_fr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='presentation.About')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'verbose_name': 'Item',
            },
        ),
    ]
