BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBB  gettext('Disciplines List')  BBBBBBBB BBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXXX
    XX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB XXXXXXXXXX XXXXXXXXXXXXX gettext('Add Discipline ') XXXX
  XXXX
  XXXX gettext('Disciplines List') XXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
          XXXX
              XXXX gettext('Name') XXXXX
          XXXXX
      XXXXXXXX
      XXXXXXX
        BBB B BB BBBBBBBBBBB
          XXX XXXXXXXXXX XXXXXXXX
              XXXX 
               	 
              XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB  BBBBX XXX XXXXXXXXX XXXXXXX XXXXXXXXXXX  XXXX
              XXXXX
          XXXXX
        BBBBBB
      XXXXXXXX
  XXXXXXXX
XXXXXX
BBBBBBBB BBBBBBB