BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBB  gettext('Domains List')  BBBBBBBB BBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXXX
    XX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXX XXXXXXXXXXXXX gettext('Add Domain ') XXXX
  XXXX
  XXXX gettext('Domain List') XXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
          XXXX
              XXXX gettext('Name') XXXXX
          XXXXX
      XXXXXXXX
      XXXXXXX
        BBB B BB BBBBBBB
          XXX XXXXXXXXXX XXXXXXXX
              XXXX 
               	XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX  XXXX 
              XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBX XXX XXXXXXXXX XXXXXXX XXXXXXXXXXX  XXXX
              XXXXX
          XXXXX
        BBBBBB
      XXXXXXXX
  XXXXXXXX
XXXXXX
BBBBBBBB BBBBBBB