# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bachelor',
            name='option_en',
        ),
        migrations.RemoveField(
            model_name='bachelor',
            name='option_fr',
        ),
        migrations.RemoveField(
            model_name='master',
            name='speciality_en',
        ),
        migrations.RemoveField(
            model_name='master',
            name='speciality_fr',
        ),
    ]
