# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-01 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0002_auto_20161025_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='pdf_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='pdf_fr',
        ),
    ]
