# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug_fr',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
