# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20161007_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_fr',
            field=models.TextField(null=True),
        ),
    ]
