BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB  gettext('Academic Years List')  BBBBBBBB BBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
	XX XXXXXXXXXXXXXXXXXXX
		XX XXXXXBBB BBBBBBBBBBBBBBBBBBB XXXXXXXXXX XXXXXXXXXXXXX gettext('Create Academic Year') XXXX
	XXXX
	XX XXXXXXXXXXXXXXXXXXX
	XXXX
 	XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXX
		  
		XXXXXXXX
		XXXXXXX
		BBB BBBB BB BBBBB  
			XXX XXXXXXXXXX XXXXXXXX
				XXXX XXXXX
				XXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX
			XXXXX
		BBBBBB
		XXXXXXXX
  	XXXXXXXX
XXXXXX
BBBBBBBB BBBBBBB