BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext('Staff Members') BBBBBBBB BBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXXX
    XX XXXXXBBB BBBBBBBBBBBBBBBBBB XXXXXXXXXX XXXXXXXXXXXXX gettext('Add Scolar ') XXXX
    XX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXX XXXXXXXXXXXXX gettext('Add Lecturer ') XXXX
    XX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXX XXXXXXXXXXXXX gettext('Add Commercial ') XXXX
    XX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXX XXXXXXXXXXXXX gettext('Add Allianza Admin ') XXXX
  XXXX
  XXXX gettext('Scolarity Members List') XXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
          XXXX
              XXXX gettext('Name') XXXXX
              XXXX gettext('Email') XXXXX
              XXXX gettext('Phone') XXXXX
              XXXX gettext('Residence') XXXXX
          XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBBBB BB BBBBBBB
          XXX XXXXXXXXXX XXXXXXXX
              XXXX XXXXX
              XXXXXXXXX
              XXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX  XXXX
              XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                BBBB
                  XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBBBB
              XXXXX
          XXXXX
        BBBBBB
      XXXXXXXX
  XXXXXXXX

  XXXX

XXXX gettext('Allianza Admins Members List') XXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
          XXXX
              XXXX gettext('Name') XXXXX
              XXXX gettext('Email') XXXXX
          XXXXX
      XXXXXXXX
      XXXXXXX
        BBB B BB BBBBBBBBBBBBB
          XXX XXXXXXXXXX XXXXXXXX
              XXXX XXXXX
              XXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                BBBB
                  XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBBBB
              XXXXX
          XXXXX
        BBBBBB
      XXXXXXXX
  XXXXXXXX

  XXXX

  XXXX gettext('Lecturers Members List') XXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
          XXXX
              XXXX gettext('Name') XXXXX
              XXXX gettext('Email') XXXXX
              XXXX gettext('Phone') XXXXX
              XXXX gettext('Residence') XXXXX
          XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBBBBBB BB BBBBBBBBB
          XXX XXXXXXXXXX XXXXXXXX
              XXXX XXXXX
              XXXXXXXXX
              XXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX  XXXX
              XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                BBBB
                  XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBBBB
              XXXXX
          XXXXX
        BBBBBB
      XXXXXXXX
  XXXXXXXX

  XXXX

  XXXX gettext('Commercials List') XXXXX


  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
          XXXX
              XXXX gettext('Name') XXXXX
              XXXX gettext('Email') XXXXX
              XXXX gettext('Phone') XXXXX
              XXXX gettext('Residence') XXXXX
          XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBBBBBBBB BB BBBBBBBBBBB
          XXX XXXXXXXXXX XXXXXXXX
              XXXX XXXXX
              XXXXXXXXX
              XXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
              XX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX  XXXX
              XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                BBBB
                  XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBBBB
              XXXXX
          XXXXX
        BBBBBB
      XXXXXXXX
  XXXXXXXX
  XX XXXXX X XXXXXXXXXXXXX
    XX XXXXXBBB BBBBBBBBBBBBBBBBB XXXXXXXXXX XXXXXXXXXXXXX gettext('Academic Year') XXXX
  XXXX
XXXXXX
BBBBBBBB BBBBBBB
