BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
	XXXX XXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX
						BBB B BB BBBBB
							
							XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBXXXXXXXXXXX		
						BBBBBB				
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX
						XXX
							BBB BBBBBBBBBB BB BBBBBBBBBBB
								XX XXXXXXXXX  XXXX XXXXXXXX 
							BBBBBB
						XXXX
						XXXX
						BBB B BB BBBBBBBBBBB
						XXXXX
							XXX XXXXXX  XXXXX
							BBBB BBBBBBBBBBB   
								BBB B BB BBBBB
									BB BBBBBBBBBBBBBBBBB BB BBBB
										XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBXXXXXX
									BBBBB
								BBBBBB
							BBBBBBB
						XXXXXX
						BBBBBB
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
BBBBBBBB BBBBBBB