# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Domains',
                'verbose_name': 'Domain',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Domain')),
                ('domain_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Domain')),
                ('domain_fr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Domain')),
            ],
            options={
                'verbose_name_plural': 'Options',
                'verbose_name': 'Option',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Option')),
                ('option_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Option')),
                ('option_fr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Option')),
            ],
            options={
                'verbose_name_plural': 'Specialities',
                'verbose_name': 'Speciality',
            },
        ),
    ]
